modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "it_follows"
version = "${version}"
displayName = "It Follows"
authors = "Lucraft, ConnorDawn"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.it_follows]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.it_follows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.it_follows]]
modId = "architectury"
type = "required"
versionRange = "[17.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "it_follows.mixins.json"
