modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ThreeTAG/ItFollows/issues"
license = "MIT (modified)"

[[mods]]
modId = "it_follows"
version = "${version}"
displayName = "It Follows"
authors = "Lucraft, ConnorDawn"
description = '''
Be prepared for a mysterious entity hunting you through your world...
'''
#logoFile = ""

[[dependencies.it_follows]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.it_follows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.it_follows]]
modId = "architectury"
type = "required"
versionRange = "[17.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "it_follows.mixins.json"
